version: '3'
services:
  api:
    container_name: bsafe_api
    ports:
      - '3333:3333'
    build:
      dockerfile: Dockerfile
      context: .
    working_dir: /api
    volumes:
      - ./uploads:/api/uploads
    environment:
      - NODE_ENV=production
      # DATABASE
      - DATABASE_HOST=roundhouse.proxy.rlwy.net
      - DATABASE_PORT=31750
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=f14bEaAF4baEa1cfE26GAa3EEEdaAgBe
      - DATABASE_NAME=railway
      # APP
      - API_PORT=3333
      - APP_NAME=bsafe-api
      # ADMIN USER
      - APP_ADMIN_EMAIL=admin_user_email
      - APP_ADMIN_PASSWORD=admin_user_password
      # TOKENS
      - ACCESS_TOKEN_SECRET=access_token_secret
      - REFRESH_TOKEN_SECRET=refresh_token_secret
      # AWS
      - UI_URL=https://app.bsafe.pro
      - API_URL=https://api-multsig.infinitybase.com
      # DISCORD
      - DISCORD_WEBHOOK=https://discord.com/api/webhooks/1179911741568733295/Y2Re5SpoxBzwLMZfmZyHqCAIp0sr3NvXc6DCfrpMgNY7KO-bGkOJg2FBiTmJbAnvgD2b
