version: '3'
services:
  api:
    container_name: ${SOCKET_NAME}
    ports:
      - '${PORT}:${PORT}'
    build:
      dockerfile: Dockerfile
      context: .
    working_dir: /socket
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - UI_URL=${UI_URL}
      - API_URL=${API_URL}
      - SOCKET_PORT=${SOCKET_PORT}
      - SOCKET_NAME=${SOCKET_NAME}
      - SOCKET_TIMEOUT_DICONNECT=${SOCKET_TIMEOUT_DICONNECT}
