version: '3'
services:
  api:
    container_name: ${GATEWAY_NAME}
    ports:
      - '${GATEWAY_PORT}:${GATEWAY_PORT}'
    build:
      dockerfile: Dockerfile.stg
      context: .
    working_dir: /gateway
    environment:
      - API_ENVIRONMENT=${API_ENVIRONMENT}
      # DATABASE
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      # APP
      - GATEWAY_PORT=${GATEWAY_PORT}
      - GATEWAY_NAME=${GATEWAY_NAME}
      - API_URL=${API_URL}
      - FUEL_PROVIDER=${FUEL_PROVIDER}
      # TOKENS
      - API_TOKEN_SECRET=${API_TOKEN_SECRET}
      - API_TOKEN_SECRET_IV=${API_TOKEN_SECRET_IV}
