version: '3'
services:
  api:
    container_name: ${APP_NAME}
    ports:
      - '${API_PORT}:${API_PORT}'
    build:
      dockerfile: Dockerfile.stg
      context: .
    working_dir: /gateway
    environment:
      - API_ENVIRONMENT=${API_ENVIRONMENT}
      # DATABASE
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      # APP
      - API_PORT=${API_PORT}
      - APP_NAME=${API_NAME}
      - BAKO_SERVER=${BAKO_SERVER}
      - FUEL_PROVIDER=${FUEL_PROVIDER}
      # TOKENS
      - API_TOKEN_SECRET=${API_TOKEN_SECRET}
      - API_TOKEN_SECRET_IV=${API_TOKEN_SECRET_IV}
