on:
  push:
    branches: [ FEAT/get-ci ]

name: Prod Deploy to Amazon ECS

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.BAKO_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.BAKO_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

